version: 2
jobs:
  build:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: master
    steps:
      - checkout
      - run:
          name: update
          command: 'apt-get update -qq'
      - run:
          name: sudo
          command: 'apt-get install -y sudo'
      - run:
          name: dependencies
          command: 'apt-get install -y python g++-4.9'
      - run:
          name: compile
          command: 'make sdebug'
      - run:
          name: download-data
          command: 'cd ./streaming/data && wget https://github.com/sbustreamspot/sbustreamspot-data/raw/master/all.tar.gz && tar -xzf all.tar.gz'
      - run:
          name: prepare-data
          command: 'cd ./streaming/data && make youtube && make attack'
          no_output_timeout: '90m'
      - run:
          name: run-graphchi
          command: 'make run_attack && make run_youtube'
          no_output_timeout: '120m'
      - run:
          name: analyze
          command: 'cd ./streaming/analyze && python model.py --train_dir train-data --test_dir test-data > out.txt'
          no_output_timeout: '90m'
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              mkdir -p output
              cd output
              mv ../streaming/analyze/out.txt .
              git status
              # is there any change
              if ! git diff-index --exit-code --quiet HEAD; then
                echo 'Committing...'
                git commit -a -m "[ci skip] CircleCI's commit ${CIRCLE_SHA1}"
                git push -q https://${GH_TOKEN}@github.com/crimson-unicorn/graphchi-cpp.git $TARGET_BRANCH
              else
                echo 'Nothing to commit.'
              fi
            fi
